version: '3.3'   
services:                                                                                                                          
  uptime-kuma:                                                                                                                     
    image: louislam/uptime-kuma:1                                                                                                  
    container_name: uptime-kuma                                                                                                    
    volumes:                                                                                                                       
      - uptime-kuma-data:/app/data 
    networks:
      - core_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.uptimekuma-secure.entrypoints=websecure"
      - "traefik.http.routers.uptimekuma-secure.rule=Host(`ptmkm.enrique.pw`)"  # || Host(`www.masiptv.net`)" # cambia el dominio por el de tu web     
      - "traefik.http.services.uptimekuma-websocket.loadbalancer.server.port=3001"
    #ports:                                                                                                                         
    #  - 3001:3001  # :                                                                                  
    restart: always 
volumes:
   uptime-kuma-data:
networks:
    core_proxy:
      external: true