version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - bw-data:/data
    networks:
      - core_proxy
    environment:
      - SIGNUPS_ALLOWED=false # Debe estar en true para poder crear usuarios nuevos. Cambiar a false cuando ya no quiera permitir mas usuarios
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.vaultwarden-ui.rule=Host(`vaultwarden.dominio.tld`)"
      - "traefik.http.routers.vaultwarden-ui.service=vaultwarden-ui"
      - "traefik.http.services.vaultwarden-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.vaultwarden-websocket.rule=Host(`vaultwarden.dominio.tld`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.vaultwarden-websocket.service=vaultwarden-websocket"
      - "traefik.http.services.vaultwarden-websocket.loadbalancer.server.port=3012"
  backup:
    image: jmqm/vaultwarden_backup:latest
    container_name: vaultwarden_backup
    volumes:
      - bw-data:/data:ro # Read-only
      - /opt/Backups:/backups

      - /etc/localtime:/etc/localtime:ro # Container uses date from host.
    environment:
      - DELETE_AFTER=30
      - CRON_TIME=00 00 * * * # Runs at 12:00 AM.
      - UID=0
      - GID=0
      
    networks:
      - core_proxy
volumes:
  bw-data:
networks:
  core_proxy:
    external: true